version: "3.7"

services:
  db:
    build: .
    image: my-provisioned-db:latest
    container_name: myDB
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      # PATCH_HISTORY_DB: master
      # PATCH_HISTORY_SCHEMA: dbo
      PATCH_HISTORY_TABLE: PATCH_HISTORY
    volumes:
      - mssql:/var/opt/mssql
    ports:
      - "1433:1433"

volumes:
  mssql:
    name: my-provisioned-db
