IF DB_ID('$(PATCH_HISTORY_DB)') IS NULL BEGIN
	CREATE DATABASE [$(PATCH_HISTORY_DB)]
END
GO

USE [$(PATCH_HISTORY_DB)]
GO

CREATE TABLE [$(PATCH_HISTORY_SCHEMA)].[$(PATCH_HISTORY_TABLE)]
(
	PATCH_VERSION_CD NVARCHAR(15) PRIMARY KEY,
	PATCH_FILE_NM NVARCHAR(255),
	PATCH_COMMENTS_TXT NVARCHAR(255),
	PATCH_APPLIED_DTE DATETIME DEFAULT GETDATE()
)
GO

SELECT "Provision complete!"
GO
