IF DB_ID('$(PATCH_HISTORY_DB)') IS NULL BEGIN
	CREATE DATABASE [$(PATCH_HISTORY_DB)]
END
GO

USE [$(PATCH_HISTORY_DB)]
GO

-- https://stackoverflow.com/questions/614476/storing-sha1-hash-values-in-mysql
CREATE TABLE [$(PATCH_HISTORY_SCHEMA)].[$(PATCH_HISTORY_TABLE)]
(
	PATCH_FILE_NM NVARCHAR(255),
	PATCH_HASH_TXT CHAR(40),
	PATCH_COMMENTS_TXT NVARCHAR(255),
	PATCH_APPLIED_DTE DATETIME DEFAULT GETDATE(),
	PRIMARY KEY (PATCH_FILE_NM, PATCH_HASH_TXT)
)
GO

SELECT "Provision complete!"
GO
